import { InterestType } from "../types/InterestType";

export const INTERESTS: InterestType[] = [
  { id: "0", name: "Collectible" },
  { id: "1", name: "Photography" },
  { id: "2", name: "Music" },
  { id: "3", name: "Electronic" },
  { id: "4", name: "Art" },
  { id: "5", name: "Domain Names" },
  { id: "6", name: "Sports Trading Cards" },
  { id: "7", name: "Utility" },
  { id: "8", name: "Virtual Worlds" },
  { id: "9", name: "Magnets" },
  { id: "10", name: "Podcast" },
  { id: "11", name: "Performance Arts" },
  { id: "12", name: "Space" },
  { id: "13", name: "AI" },
  { id: "14", name: "Literature" },
  { id: "15", name: "Poetry" },
  { id: "16", name: "Cartoon" },
  { id: "17", name: "3D" },
  { id: "18", name: "2D" },
  { id: "19", name: "2D animation" },
  { id: "20", name: "3D animation" },
  { id: "21", name: "Claymation" },
  { id: "22", name: "Stop Motion" },
  { id: "23", name: "Horror" },
  { id: "24", name: "Gaming" },
  { id: "25", name: "Greek Mythology" },
  { id: "26", name: "Roman Mythology" },
  { id: "27", name: "Norse Mythology" },
  { id: "28", name: "Celtic Mythology" },
  { id: "29", name: "Egyptian Mythology" },
  { id: "30", name: "Religious" },
  { id: "31", name: "Spiritual" },
  { id: "32", name: "Political" },
  { id: "33", name: "Sci Fi" },
  { id: "34", name: "Fantasy" },
  { id: "35", name: "Anime" },
  { id: "36", name: "Historical" },
  { id: "37", name: "Steampunk" },
  { id: "38", name: "Landscapes" },
  { id: "39", name: "Portraits" },
  { id: "40", name: "Wild Life" },
  { id: "41", name: "Nature" },
  { id: "42", name: "Abstract" },
  { id: "43", name: "Whimsical" },
];
