export type LeaderboardType = {
  contract_address: string;
  logo_url: string;
  contract_name: string;
  owns_total: number;
  items_total: number;
  // rank: number;
  // iconUrl: string;
  // contractName: string;
  // productPath: string;
  // baseCurrency: string;
  // isSalesOnly: boolean;
  // value: number;
  // valueUSD: number;
  // platform: number;
  // buyers: number;
  // sellers: number;
  // owners: number;
  // transactions: number;
  // previousValue: number;
  // previousValueUSD: number;
};
